name: Validation

on:
  push:
    paths:
      - "hashes/**"
      - ".github/workflows/validation.yml"
  pull_request:
    paths:
      - "hashes/**"
      - ".github/workflows/validation.yml"
  workflow_dispatch:

jobs:
  build:
    name: Validate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install atian tools
        uses: ate47/setup-acts@v1
        with:
          version: "2.21.1"
      - name: Validate hashes
        shell: pwsh
        run: scripts/validate.ps1
      - name: Build hashes (WNI)
        shell: pwsh
        run: scripts/compile.ps1 -ext wni
